# Numpy

Numpy stands for Numerical Python.

It gives us all dimensional array(n-d array)

#### How to make an Array

"as np" is an alias, it is done so that we dont have to write numpy.array everywhere for example, we can just write np.array

In [3]:
import numpy as np

a=[1,2,3]
b=np.array(a)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
import numpy as np
a=[1,2,3,'1','asfd',8.7]
b=np.array(a)
b

array(['1', '2', '3', '1', 'asfd', '8.7'], dtype='<U11')

Note : This converts all to string type.
    If we want type control we have to do b=np.array(a,dtype=int)

#### Other ways to make arrays

In [6]:
import numpy as np

a=np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [7]:
b=np.ones(5,dtype=int)
b

array([1, 1, 1, 1, 1])

In [8]:
c=np.zeros(3)
c

array([0., 0., 0.])

In [19]:
d=np.zeros((2,4),dtype=int)
d

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [21]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
a = np.arange(2,10)
a

array([2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
a = np.arange(2,10,2)
a

array([2, 4, 6, 8])

In [27]:
a = np.linspace(2,10)
a

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

##### the above creates an array in btw 2 and 10 with 50 intervals(default)

In [29]:
b = np.linspace(2,10,4)
b

array([ 2.        ,  4.66666667,  7.33333333, 10.        ])

In [30]:
c = np.identity(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
c = np.eye(3,4)
c

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

eye is used for n*m type matrox and identity for n*n type

In [33]:
d = np.random.rand(3)
d

array([0.24890227, 0.96738646, 0.63469419])

In [35]:
d = np.random.rand(2,3)
d

array([[0.49622841, 0.03377578, 0.8149437 ],
       [0.15623976, 0.87169652, 0.04563995]])

In [43]:
d = np.random.randint(100)
d

36

In [100]:
e = np.random.randint(0,10,(3,3))
e

array([[5, 1, 7],
       [6, 0, 3],
       [5, 5, 2]])

#### Accesing Elements and checking shape etc.

In [47]:
a=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
b=np.array(a)
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [48]:
print(b.shape)
print(b.dtype)
print(b.strides)
print(b.data)

(4, 3)
int32
(12, 4)


In [46]:
# Stride refers to how many bites it takes to cross a row, and how many bytes each data type takes

In [50]:
print(b[2][2])
print(b[2,1])
# Note either way works for Numpy

9
8


In [55]:
print(b[2][:3])
print(b[2,:3])

[7 8 9]
[7 8 9]


In [56]:
print(b[:,:])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


#### Numerical Functions


In [59]:
import numpy as np

a = np.arange(5)
b = np.arange(6,11)
print(a)
print(b)

[0 1 2 3 4]
[ 6  7  8  9 10]


In [62]:
a+100

array([100, 101, 102, 103, 104])

In [64]:
c = a + b
c

array([ 6,  8, 10, 12, 14])

In [66]:
d = a*b
d

array([ 0,  7, 16, 27, 40])

In [68]:
e = a//b
e

array([0, 0, 0, 0, 0], dtype=int32)

In [70]:
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin())
print(a.max())
print(a.argmax())

[0 1 2 3 4]
10
2.0
0
0
4
4


In [72]:
print(a)
print(b)
c=a>b
print(c)
print(np.logical_or(a,b))
print(np.logical_and(a,b))
print(np.logical_not(b))

[0 1 2 3 4]
[ 6  7  8  9 10]
[False False False False False]
[ True  True  True  True  True]
[False  True  True  True  True]
[False False False False False]


#### Additional Benifical Functions

In [79]:
import numpy as np

b=[1,2,3,4,56,34,23,12,56,67]
a=np.array(b)
a

array([ 1,  2,  3,  4, 56, 34, 23, 12, 56, 67])

In [81]:
c = a[a>10]
c

array([56, 34, 23, 12, 56, 67])

In [82]:
c = a[(a>10)& (a<50)]
c

array([34, 23, 12])

In [84]:
a[:3]=200
print(a)

[200 200 200   4  56  34  23  12  56  67]


To find the index of a element in an array

In [87]:
print(a[a==200])

[200 200 200]


In [88]:
ind = np.where(a==200)
ind

(array([0, 1, 2], dtype=int64),)

#### For 2-D arrays

In [102]:
import numpy as np
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(a)

bool_arr = b>5
print(bool_arr)
####
c = b[bool_arr]
print(c)
####
b[bool_arr]=100
print(b)
####

[[False False False]
 [False False  True]
 [ True  True  True]]
[6 7 8 9]
[[  1   2   3]
 [  4   5 100]
 [100 100 100]]


#### Broadcasting

 Everything we have done with 2 arrays is that they are of same dimensions, ie they are both M*n

But what if you get 1 array which is 2*3 and another wchich is 3*2, we cant do much

Broadcasting gives us directions as to what to do


In [103]:
import numpy as np 

A = np.array([5, 7, 3, 1]) 
B = np.array([90, 50, 0, 30]) 

# array are compatible because of same Dimension 
c = a * b 
print (c) 


[[  1   4   9]
 [ 16  25 600]
 [700 800 900]]


In [104]:
#The above case is okay as dimensions match

if it is 3*3 and 1*3, this is also okay as the last values (3&3) are same

But if it's 2*3 types and 3*2 then it gives error'

WHat we can do here is transpose 2*3 to 3*2 and try to make it work